dist: xenial
language: python

matrix:
  include:
  - python: "2.7"
    env: TORNADO_VERSION=4.1   NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8
  - python: "2.7"
    env: TORNADO_VERSION=4.4.3 NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8
  - python: "2.7"
    env: TORNADO_VERSION=4.5.3 NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3
  - python: "2.7"
    env: TORNADO_VERSION=5.1.1 NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3

  - python: "3.4"
    env: TORNADO_VERSION=4.5.3 NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8
  - python: "3.4"
    env: TORNADO_VERSION=5.1.1 NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3

  - python: "3.5"
    env: TORNADO_VERSION=4.5.3 NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8
  - python: "3.5"
    env: TORNADO_VERSION=5.1.1 NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3

  - python: "3.6"
    env: TORNADO_VERSION=4.5.3 NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8
  - python: "3.6"
    env: TORNADO_VERSION=5.1.1 NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3
  - python: "3.6"
    env: TORNADO_VERSION=6.0.3 NSQ_DOWNLOAD=nsq-1.2.0.linux-amd64.go1.12.9

  - python: "3.7"
    env: TORNADO_VERSION=4.5.3 NSQ_DOWNLOAD=nsq-1.0.0-compat.linux-amd64.go1.8
  - python: "3.7"
    env: TORNADO_VERSION=5.1.1 NSQ_DOWNLOAD=nsq-1.2.0.linux-amd64.go1.12.9

  - python: "3.8"
    env: TORNADO_VERSION=5.1.1 NSQ_DOWNLOAD=nsq-1.2.0.linux-amd64.go1.12.9
  - python: "3.8"
    env: TORNADO_VERSION=6.0.3 NSQ_DOWNLOAD=nsq-1.2.0.linux-amd64.go1.12.9

script:
  - ./travis_test.sh
notifications:
  email: false
